In [18]:
import numpy as np
import pandas as pd
from sklearn import tree
import scipy
import matplotlib.pyplot as plt
import graphviz
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [2]:
# Import training & test set
# separate training into 2 arrays: features & labels

training = pd.read_csv('pitchclassificationtrain.csv')
test = pd.read_csv('pitchclassificationtest.csv')


train_features = training.drop("type",axis = 1)
#train_features = pd.DataFrame(train_features)

train_labels = training.type
#train_labels = pd.DataFrame(train_labels)


In [35]:
test.head(5)

test.to_csv("simple_test.csv")

In [3]:
training.head(5)

pitchid  pitcherid  yearid  height  initspeed    breakx    breakz  \
0        1          5       1      72  83.774424 -1.293106  4.451670   
1        2          5       1      72  89.642714 -6.550556  7.993455   
2        3          4       1      72  91.750648 -6.985574  8.991264   
3        4          5       1      72  83.189766 -2.549204  4.844714   
4        5          2       1      80  92.698738 -5.216516  7.267769   

   initposx  initposz  extension     spinrate  type  
0 -1.330641  6.065956   6.317961  1386.459243     3  
1 -1.556463  5.719125   6.119526  1963.264977     9  
2 -2.055134  5.780312   6.201200  2360.758263     9  
3 -1.001020  6.240138   6.074156   858.997788     7  
4 -2.097643  5.776138   6.212281  2060.155099     9

In [4]:
train_features[:1]

pitchid  pitcherid  yearid  height  initspeed    breakx   breakz  initposx  \
0        1          5       1      72  83.774424 -1.293106  4.45167 -1.330641   

   initposz  extension     spinrate  
0  6.065956   6.317961  1386.459243

In [5]:
train_labels[:1]

0    3
Name: type, dtype: int64

In [55]:
# feature scaling

train_features[train_features.dtypes[(train_features.dtypes == 'float64')|(train_features.dtypes == 'int64')].index.values].hist(figsize=[1,1,11])

TypeError: from_bounds() takes 4 positional arguments but 5 were given

In [20]:
# learn the distribtuion of labels, balance the dataset

train_labels.value_counts()

10    3102
9     2952
2     1483
4     1330
7      901
8      674
3      205
Name: type, dtype: int64

In [37]:
test['prediction'].value_counts()

9     2960
10    2777
4     2379
2     2377
8     1042
3      560
7      259
Name: prediction, dtype: int64

In [ ]:
# feature selection (remove low variance, univariate (selectKBest, RFECV, tree-based,  )
# figure out each variables importance to label

In [13]:
# Building 



# initial method

intial = tree.DecisionTreeClassifier()
initial = intial.fit(train_features,train_labels)

#min_samples_leaf=5 method

#simple = 

# gini method

# entropy method

# 10 fold cross validation method

# leave one out cross validation

In [14]:
dot_data = tree.export_graphviz(intial, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("pitch_type") 

# VERY COMPLEX, good training accuracy but probably bad testing accuracy

'pitch_type.pdf'

In [21]:
# test on training set 

X_train, X_test, y_train, y_test = train_test_split(  
    train_features, train_labels, test_size = 0.3, random_state = 100) 

def prediction(X_test, clf_object):
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 

def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
    


In [25]:
# 100% train accuracy
y_pred = prediction(train_features, initial)
cal_accuracy(train_labels,y_pred)

Predicted values:
[3 9 9 ... 2 2 2]
Confusion Matrix:  [[1483    0    0    0    0    0    0]
 [   0  205    0    0    0    0    0]
 [   0    0 1330    0    0    0    0]
 [   0    0    0  901    0    0    0]
 [   0    0    0    0  674    0    0]
 [   0    0    0    0    0 2952    0]
 [   0    0    0    0    0    0 3102]]
Accuracy :  100.0
Report :                precision    recall  f1-score   support

           2       1.00      1.00      1.00      1483
           3       1.00      1.00      1.00       205
           4       1.00      1.00      1.00      1330
           7       1.00      1.00      1.00       901
           8       1.00      1.00      1.00       674
           9       1.00      1.00      1.00      2952
          10       1.00      1.00      1.00      3102

   micro avg       1.00      1.00      1.00     10647
   macro avg       1.00      1.00      1.00     10647
weighted avg       1.00      1.00      1.00     10647



In [24]:
# 100% test accuracy (inside train)
y_pred = prediction(X_test, initial)
cal_accuracy(y_test,y_pred)

Predicted values:
[ 3  2  4 ... 10  2  7]
Confusion Matrix:  [[435   0   0   0   0   0   0]
 [  0  57   0   0   0   0   0]
 [  0   0 408   0   0   0   0]
 [  0   0   0 282   0   0   0]
 [  0   0   0   0 194   0   0]
 [  0   0   0   0   0 912   0]
 [  0   0   0   0   0   0 907]]
Accuracy :  100.0
Report :                precision    recall  f1-score   support

           2       1.00      1.00      1.00       435
           3       1.00      1.00      1.00        57
           4       1.00      1.00      1.00       408
           7       1.00      1.00      1.00       282
           8       1.00      1.00      1.00       194
           9       1.00      1.00      1.00       912
          10       1.00      1.00      1.00       907

   micro avg       1.00      1.00      1.00      3195
   macro avg       1.00      1.00      1.00      3195
weighted avg       1.00      1.00      1.00      3195

Predicted values:
[ 3  2  4 ... 10  2  7]
Confusion Matrix:  [[435   0   0   0   0   0   0]
 [  

In [31]:
# basic test

y_pred = prediction(test, initial)


ValueError: Number of features of the model must match the input. Model n_features is 11 and input n_features is 12 

In [7]:
# Visualise your tree as you are training by using the export function. Use max_depth=3 as an initial tree depth to get a feel for how the tree is fitting to your data, and then increase the depth.

# plot: tree.plot_tree(clf.fit(iris.data, iris.target)) 

# or 

# import graphviz 
#>>> dot_data = tree.export_graphviz(clf, out_file=None) 
#>>> graph = graphviz.Source(dot_data) 
#>>> graph.render("iris") 
#dot_data = tree.export_graphviz(clf, out_file=None, 
#...                      feature_names=iris.feature_names,  
#...                      class_names=iris.target_names,  
#...                      filled=True, rounded=True,  
#...                      special_characters=True)  
#>>> graph = graphviz.Source(dot_data)  
#>>> graph 

# or 

#from sklearn.datasets import load_iris
#>>> from sklearn.tree import DecisionTreeClassifier
#>>> from sklearn.tree.export import export_text
#>>> iris = load_iris()
#>>> X = iris['data']
#>>> y = iris['target']
#>>> decision_tree = DecisionTreeClassifier(random_state=0, max_depth=2)
#>>> decision_tree = decision_tree.fit(X, y)
#>>> r = export_text(decision_tree, feature_names=iris['feature_names'])
#>>> print(r)